# Substitute missing icon
sedit "s:Icon=applications-education:Icon=applications-science:1" data/xfce/xfce-education.directory.in  &&

OPTS+=" --disable-static \
        --disable-debug"

default_build
